_layouts/default.html
_posts/2015-03-04-being-in-the-midst-of-a-growing-company.markdown
_sass/_layout.scss
css/main.scss
index.html

Updated header styles, removed hero, updated type and image treatment for post lists.

Design updates

---

client/components/layout/index.jsx
client/styling/root.less

Creating separate branch to prevent collision with Colin's work
Changes: 
- Make header and sidebar navigation fixed
- Pressing 'MongoDB Design' logo redirects to welcome page
cc: @colinkeany @marcgurney

Running Branch for Nav Changes

---

client/components/ui-design-system/buttons/index.jsx
client/components/ui-design-system/forms/index.jsx
client/styling/buttons.less
client/styling/forms.less
client/styling/typography.less

- Added info and darker buttons
- Added input states for success and error

js-feat-input-form

---

client/styling/navigation.less

Minor tweaks to make the navigation sidebar vertically scrollable as we continue to add more components to the library.

Small PR: Make Sidebar Vertically Scrollable

---

client/components/brand-design-system/index.jsx
client/components/layout/index.jsx
client/components/ui-design-system/index.jsx
client/styling/navigation.less

Small PR that makes sidebar links green when being the active page. 
Side note: We should consider upgrading `react-router` from v2 to v4 in the near future.

Sidebar Active State

---

client/components/ui-design-system/components/tables/index.jsx
client/components/ui-design-system/components/tabs/index.jsx
client/styling/code.less
client/styling/navigation.less
client/styling/tabs.less
client/styling/typography.less
client/styling/view-modal.less

Small PR that modifies a few components we've added so far.
**Tabs**
* Remove links that take the user to mongodb.com
* Add pointer cursor 
**Table**
* Remove links that take the user to DS site homepage
**Links**
* Add pointer cursor
* Add not allowed cursor for disabled links 
**Code Snippet**
* Remove blue focus outline from copy button
**Modal**
* Remove blue focus outline from close button

Fix Small Component Bugs

---

client/components/ui-design-system/components/view-modal/index.jsx
client/components/ui-design-system/components/view-modal/react-view-modal.jsx
client/components/ui-design-system/react-components/Modal.js
client/routes.jsx
client/styling/view-modal.less

To Do:
Great job @sampoonachot! Learn so quick! ✨

Import Modal React Component from Cloud

---

client/components/ui-design-system/base-styles/colors/index.jsx
client/styling/palette.less
client/styling/root.less

Add darker greens and tones. @marcgurney Does this look good to you?

Updated green

---

client/components/ui-design-system/components/code/index.jsx
client/components/ui-design-system/components/code/react-copyablecommand.jsx
client/components/ui-design-system/react-components/CopyableCommand.js
client/components/ui-design-system/react-components/Tooltip.js
client/routes.jsx
package.json

Add Copyable Command React Component

---

client/components/ui-design-system/components/buttons/react-buttons.jsx
client/components/ui-design-system/components/code/react-copyablecommand.jsx
client/components/ui-design-system/react-components/CopyableCommand.js

* fixed fullwidth snippet
* removed wraptext
* removed button-is-uppercase 
* sanity checked html and react code

fixed fullwidth snippet for copyable command component

---

client/components/ui-design-system/components/banners/index.jsx
client/components/ui-design-system/components/banners/react-banners.jsx
client/components/ui-design-system/react-components/Alert.js
client/routes.jsx
client/styling/alert.less
client/styling/palette.less
client/styling/root.less

Added CSS and React version of alerts and a few styles / colors they needed.

React banners

---

client/components/ui-design-system/components/view-modal/index.jsx
client/styling/view-modal.less

- replaced `div` with `header` and `footer` to match react component
- removed border padding on html component and added hr tags

sanity checked html and react for modal component

---

client/components/ui-design-system/components/layouts/index.jsx
client/components/ui-design-system/components/layouts/react-layouts.jsx
client/components/ui-design-system/react-components/SplashView.js

- in splashview.js, replaced `section` with `div`
- removed repetitive classname `button` in react button
- fixed minor styling issues

sanity check html and react for layouts component

---

client/components/ui-design-system/base-styles/colors/index.jsx
client/components/ui-design-system/base-styles/typography/index.jsx
client/components/ui-design-system/components/banners/index.jsx
client/components/ui-design-system/components/bubbles/index.jsx
client/components/ui-design-system/components/buttons/index.jsx
client/components/ui-design-system/components/buttons/react-buttons.jsx
client/components/ui-design-system/components/code/index.jsx
client/components/ui-design-system/components/code/react-copyablecommand.jsx
client/components/ui-design-system/components/forms/index.jsx
client/components/ui-design-system/components/layouts/index.jsx
client/components/ui-design-system/components/layouts/react-layouts.jsx
client/components/ui-design-system/components/lists/index.jsx
client/components/ui-design-system/components/tables/index.jsx
client/components/ui-design-system/components/tabs/index.jsx
client/components/ui-design-system/components/view-modal/index.jsx
client/components/ui-design-system/components/view-modal/react-view-modal.jsx
client/components/ui-design-system/guidelines/grid/index.jsx
client/components/ui-design-system/resources/index.jsx
client/components/ui-design-system/welcome/index.jsx
client/components/ui-design-system/welcome/principles.jsx

- removed some utility classes (padding) to reduce extra white space on the page
- added the code snippet for dark theme table

Fix padding

---

client/components/ui-design-system/components/forms/index.jsx
client/components/ui-design-system/components/rich-forms/index.jsx

This small PR fixes some minor console errors thrown at the forms / rich forms page.

Fix console errors

---

client/components/ui-design-system/components/forms/index.jsx
client/components/ui-design-system/components/view-modal/react-view-modal.jsx

changed language html to jsx in form inputs component

added language jsx to form inputs

---

client/components/ui-design-system/components/buttons/react-buttons.jsx

Add import statements to fix react-buttons.jsx

---

client/components/ui-design-system/base-styles/icons/index.jsx
client/styling/fonts.less
client/styling/icons-table.less
client/styling/mms-icons.less
client/styling/palette.less
client/styling/root.less
config.js

Still need to add the marketing icons and maybe link out to Material and Font Awesome.

Mms icons in mms-fonts branch

---

client/index.html
client/site/ui-design-system/resources/index.jsx

Move github API call to Stitch app

---

package-lock.json
package.json

upgrade react-router to 3.2.0

---

client/site/ui-design-system/components/layouts/index.jsx
client/site/ui-design-system/components/layouts/react-layouts.jsx

added link to graphics creation wiki content; fix for react elements toggles;

PD-19 Tweak

---

client/site/ui-design-system/base-styles/colors/index.jsx

PD-58: Fix for Charts palette

---

client/site/ui-design-system/components/tabs/index.jsx

Updating out-of-date banner for tabs component!

Update out-of-date banner for Tabs Component

---

.env.example
.eslintrc.cjs
components/ContentfulRichText.tsx
components/Image.tsx
components/navigation/Navigation.tsx
components/navigation/NavigationContent.tsx
pages/component/[componentName]/documentation.tsx
pages/component/[componentName]/example.tsx
pages/component/[componentName]/guidelines.tsx
utils/getContentfulResources.ts
utils/getStaticComponent.ts

Updates content references for the new project (not PoC project)

Refactor for new project

---

components/PropTooltipContent.tsx

Fixes PropTooltip component so that it renders properly in darkmdoe

---

components/ContentstackRichText/ContentstackChildren.tsx
components/ContentstackRichText/ContentstackEntry.tsx
components/ContentstackRichText/ContentstackRichText.tsx
components/ContentstackRichText/ContentstackText.tsx
components/ContentstackRichText/HorizontalLayout.tsx
components/ContentstackRichText/HorizontalLayoutColumn.tsx
components/ContentstackRichText/componentMap.tsx
components/ContentstackRichText/types.ts
components/ContentstackRichText/utils.ts

Updates TS types of contentstack elements
Updates Horizontal layout component

LG-2796 contentstack horizontal column block

---

README.md

Adds instructions for how to build with linked packages

Adds local build instructions

---

components/ContentstackRichText/ExampleCardBlock/ExampleCardBlock.tsx
components/ContentstackRichText/componentMap.tsx

Fixes margin on ExampleCard blocks & Table cards

Launch blockers v4_final

---

components/navigation/NavigationContent.tsx
components/pages/documentation/TSDocPropTable/TSDocPropTable.tsx

- Foundations pages were not appearing as active in side nav -- fixes that
- Increases line height of description items in PropTable

Small .design tweaks

---

components/pages/example/LiveExample.tsx

https://jira.mongodb.org/browse/LG-3309

[LG-3309] Temporarily disable code examples

---

layouts/ComponentLayout.tsx

Also fixes component display names

Updates icons to tooltips

---

layouts/ComponentLayout.tsx

LG-3364: Updates to use H1 instead of H2 elements on Component pages

---

src/utils/ContentStack/getContentstackResources.ts
src/utils/components.ts
src/utils/foundations.ts
src/utils/patterns.ts
src/utils/titleCase.ts

[LG-4754](https://jira.mongodb.org/browse/LG-4754)

LG-4754: End of Life page

---

src/app/[contentPageGroup]/[contentPage]/page.tsx
src/app/api/contentstack/entry/[contentTypeUid]/[uid]/route.ts
src/app/component/[component]/code-docs/page.tsx
src/app/component/[component]/design-docs/page.tsx
src/app/component/[component]/layout.tsx
src/app/layout.tsx
src/app/private/page.tsx
src/app/template.tsx
src/auth/client.ts
src/components/global/LogIn.tsx
src/components/global/PrivateContentWall.tsx
src/components/global/PrivateIcon.tsx
src/components/global/Search/Search.tsx
src/components/global/SideNavigation/SideNavigation.tsx
src/components/global/UserMenu.tsx
src/components/providers/SessionWrapper.tsx
src/hooks/useSession.ts
src/lib/contentStack/contentStackService.ts
src/utils/components.ts
src/utils/foundations.ts
src/utils/patterns.ts

Revert "Revert "[LG-5380, LG-5381] fix: Add back private check""
